version: '2'
services:
    page:
        image: jekyll/jekyll:4
        container_name: asociacija_page
        ports:
          - 4000:4000
        volumes:
          - .:/srv/jekyll
        command: jekyll serve -I
